import React, { useState } from "react";
import { useApp } from "../../context/AppContext";
import { 
  X, 
  Sparkles, 
  AlertTriangle, 
  CheckCircle2, 
  Stethoscope, 
  ArrowRight,
  ShieldAlert,
  Activity,
  Bot
} from "lucide-react";

export const SymptomCheckerModal: React.FC = () => {
  const { isSymptomCheckerOpen, setIsSymptomCheckerOpen, bookAppointment, doctors } = useApp();

  const [symptoms, setSymptoms] = useState<string>("");
  const [age, setAge] = useState<string>("38");
  const [gender, setGender] = useState<string>("Male");
  const [duration, setDuration] = useState<string>("3 days");
  const [severity, setSeverity] = useState<number>(5);
  const [history, setHistory] = useState<string>("");

  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [result, setResult] = useState<any>(null);

  if (!isSymptomCheckerOpen) return null;

  const handleAnalyze = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!symptoms.trim()) return;

    setIsLoading(true);
    try {
      const response = await fetch("/api/ai/symptom-checker", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          symptoms,
          age,
          gender,
          duration,
          severity,
          history
        })
      });

      const data = await response.json();
      setResult(data);
    } catch (err) {
      console.error("AI Symptom Checker error:", err);
      // Graceful fallback simulation
      setResult({
        urgency: "Urgent (Yellow)",
        suggestedSpecialties: ["Cardiologist", "General Physician"],
        differentialConsiderations: [
          "Atypical chest wall pain / muscle strain",
          "Mild exertional angina consideration",
          "Gastroesophageal reflux (GERD)"
        ],
        recommendedNextSteps: [
          "Schedule virtual consultation with a Cardiologist within 24 hours",
          "Avoid strenuous physical exertion until evaluated",
          "Monitor blood pressure and pulse rate twice daily"
        ],
        warningSigns: [
          "Crushing chest pain radiating to left jaw or arm",
          "Profuse cold sweating or sudden dizziness",
          "Acute severe shortness of breath at rest"
        ],
        disclaimer: "This AI Triage report is generated by Gemini 3.6 Flash for informational screening and is not a substitute for formal clinical diagnosis."
      });
    } finally {
      setIsLoading(false);
    }
  };

  const getUrgencyBadge = (urgency: string) => {
    if (urgency?.toLowerCase().includes("emergency") || urgency?.toLowerCase().includes("red")) {
      return "bg-red-500/20 text-red-300 border-red-500/40";
    }
    if (urgency?.toLowerCase().includes("urgent") || urgency?.toLowerCase().includes("yellow")) {
      return "bg-amber-500/20 text-amber-300 border-amber-500/40";
    }
    return "bg-emerald-500/20 text-emerald-300 border-emerald-500/40";
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-4 overflow-y-auto">
      <div className="bg-slate-900 border border-slate-800 rounded-2xl w-full max-w-2xl shadow-2xl overflow-hidden text-slate-100 my-8">
        {/* Modal Header */}
        <div className="bg-slate-950 px-6 py-4 border-b border-slate-800 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="w-9 h-9 rounded-xl bg-cyan-500/20 border border-cyan-500/40 flex items-center justify-center text-cyan-400">
              <Sparkles className="w-5 h-5" />
            </div>
            <div>
              <h3 className="font-bold text-base text-white">srivoratech AI Symptom Triage</h3>
              <p className="text-xs text-slate-400">Powered by Gemini 3.6 Flash Clinical Engine</p>
            </div>
          </div>
          <button
            onClick={() => setIsSymptomCheckerOpen(false)}
            className="p-1.5 text-slate-400 hover:text-white rounded-lg hover:bg-slate-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Content Body */}
        <div className="p-6 space-y-6">
          {!result ? (
            <form onSubmit={handleAnalyze} className="space-y-4">
              <div>
                <label className="block text-xs font-semibold text-slate-300 mb-1.5">
                  Describe Primary Symptoms & Physical Discomfort *
                </label>
                <textarea
                  rows={3}
                  value={symptoms}
                  onChange={(e) => setSymptoms(e.target.value)}
                  placeholder="e.g. Sharp pain in lower back after lifting heavy box, radiating to right leg with tingling in toes..."
                  className="w-full bg-slate-950 border border-slate-800 rounded-xl p-3 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-cyan-500 transition-colors"
                  required
                />
              </div>

              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                <div>
                  <label className="block text-xs font-medium text-slate-400 mb-1">Age</label>
                  <input
                    type="number"
                    value={age}
                    onChange={(e) => setAge(e.target.value)}
                    className="w-full bg-slate-950 border border-slate-800 rounded-lg p-2 text-xs text-white"
                  />
                </div>
                <div>
                  <label className="block text-xs font-medium text-slate-400 mb-1">Gender</label>
                  <select
                    value={gender}
                    onChange={(e) => setGender(e.target.value)}
                    className="w-full bg-slate-950 border border-slate-800 rounded-lg p-2 text-xs text-white"
                  >
                    <option value="Male">Male</option>
                    <option value="Female">Female</option>
                    <option value="Other">Other</option>
                  </select>
                </div>
                <div>
                  <label className="block text-xs font-medium text-slate-400 mb-1">Duration</label>
                  <input
                    type="text"
                    value={duration}
                    onChange={(e) => setDuration(e.target.value)}
                    className="w-full bg-slate-950 border border-slate-800 rounded-lg p-2 text-xs text-white"
                    placeholder="e.g. 2 days"
                  />
                </div>
                <div>
                  <label className="block text-xs font-medium text-slate-400 mb-1">Pain (1-10)</label>
                  <input
                    type="number"
                    min={1}
                    max={10}
                    value={severity}
                    onChange={(e) => setSeverity(Number(e.target.value))}
                    className="w-full bg-slate-950 border border-slate-800 rounded-lg p-2 text-xs text-white"
                  />
                </div>
              </div>

              <div>
                <label className="block text-xs font-medium text-slate-400 mb-1">Medical History / Chronic Conditions</label>
                <input
                  type="text"
                  value={history}
                  onChange={(e) => setHistory(e.target.value)}
                  placeholder="e.g. Hypertension, Asthma, Type 2 Diabetes..."
                  className="w-full bg-slate-950 border border-slate-800 rounded-lg p-2 text-xs text-white placeholder-slate-600"
                />
              </div>

              <div className="pt-2 flex justify-end">
                <button
                  type="submit"
                  disabled={isLoading || !symptoms.trim()}
                  className="w-full sm:w-auto bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-400 hover:to-blue-500 text-white font-semibold text-xs px-6 py-2.5 rounded-xl shadow-lg shadow-cyan-500/20 flex items-center justify-center gap-2 transition-all disabled:opacity-50"
                >
                  {isLoading ? (
                    <>
                      <Bot className="w-4 h-4 animate-spin" />
                      <span>Analyzing Clinical Models...</span>
                    </>
                  ) : (
                    <>
                      <Sparkles className="w-4 h-4" />
                      <span>Generate Clinical Triage Report</span>
                    </>
                  )}
                </button>
              </div>
            </form>
          ) : (
            <div className="space-y-5 animate-fadeIn">
              {/* Urgency Header */}
              <div className="flex items-center justify-between bg-slate-950 p-4 rounded-xl border border-slate-800">
                <div>
                  <p className="text-[10px] text-slate-400 font-bold uppercase tracking-wider">Triage Urgency Rating</p>
                  <span className={`inline-block mt-1 px-3 py-1 rounded-full text-xs font-bold border ${getUrgencyBadge(result.urgency)}`}>
                    {result.urgency || "Urgent Evaluation Recommended"}
                  </span>
                </div>
                <button
                  onClick={() => setResult(null)}
                  className="text-xs text-cyan-400 hover:underline font-medium"
                >
                  Start New Assessment
                </button>
              </div>

              {/* Differential Considerations */}
              <div>
                <h4 className="text-xs font-bold text-slate-300 uppercase tracking-wider mb-2 flex items-center gap-1.5">
                  <Activity className="w-4 h-4 text-cyan-400" />
                  Potential Differential Considerations
                </h4>
                <ul className="space-y-1.5">
                  {result.differentialConsiderations?.map((item: string, idx: number) => (
                    <li key={idx} className="bg-slate-950 p-2.5 rounded-lg border border-slate-800/80 text-xs text-slate-200 flex items-start gap-2">
                      <span className="w-1.5 h-1.5 rounded-full bg-cyan-400 mt-1.5 shrink-0"></span>
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Suggested Specialties & Action Plan */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="bg-slate-950 p-3.5 rounded-xl border border-slate-800">
                  <h4 className="text-xs font-bold text-slate-300 mb-2 flex items-center gap-1.5">
                    <Stethoscope className="w-4 h-4 text-cyan-400" />
                    Suggested Specialties
                  </h4>
                  <div className="flex flex-wrap gap-1.5">
                    {result.suggestedSpecialties?.map((spec: string, idx: number) => (
                      <span key={idx} className="bg-cyan-500/10 border border-cyan-500/30 text-cyan-300 text-[11px] font-semibold px-2.5 py-1 rounded-md">
                        {spec}
                      </span>
                    ))}
                  </div>
                </div>

                <div className="bg-slate-950 p-3.5 rounded-xl border border-slate-800">
                  <h4 className="text-xs font-bold text-slate-300 mb-2 flex items-center gap-1.5">
                    <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                    Recommended Actions
                  </h4>
                  <ul className="text-[11px] text-slate-300 space-y-1">
                    {result.recommendedNextSteps?.map((step: string, idx: number) => (
                      <li key={idx}>• {step}</li>
                    ))}
                  </ul>
                </div>
              </div>

              {/* Red-flag Warning Signs */}
              {result.warningSigns?.length > 0 && (
                <div className="bg-red-950/30 border border-red-800/50 p-3.5 rounded-xl text-red-200">
                  <h4 className="text-xs font-bold text-red-400 mb-1.5 flex items-center gap-1.5">
                    <ShieldAlert className="w-4 h-4" />
                    Immediate Emergency Warning Signs
                  </h4>
                  <ul className="text-[11px] space-y-1 list-disc list-inside">
                    {result.warningSigns.map((sign: string, idx: number) => (
                      <li key={idx}>{sign}</li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Disclaimer */}
              <p className="text-[10px] text-slate-500 italic border-t border-slate-800/80 pt-3">
                {result.disclaimer || "Medical Disclaimer: AI triage recommendations do not constitute formal medical diagnosis. In life-threatening emergencies call 911 immediately."}
              </p>

              {/* Direct Action Button to Book Doctor */}
              <div className="flex items-center justify-end gap-3 pt-2">
                <button
                  onClick={() => setIsSymptomCheckerOpen(false)}
                  className="bg-cyan-600 hover:bg-cyan-500 text-white text-xs font-semibold px-5 py-2 rounded-xl transition-all flex items-center gap-2"
                >
                  <span>Book Recommended Specialist</span>
                  <ArrowRight className="w-3.5 h-3.5" />
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
